apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-delete-tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-delete-tasks-api
  template:
    metadata:
      labels:
        app: todo-delete-tasks-api
    spec:
      containers:
      - name: todo-delete-tasks-api
        image: lucktodoappacr2025.azurecr.io/todo-delete-tasks-api:v2
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:devtodoappsqlsvrlav.database.windows.net,1433;Database=devtodoappdblav;Uid=sqladminlav;Pwd=Devopslav@1001;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
          

